language: python

notifications:
  email: false

services:
  - postgresql

before_script:
  - psql -c 'create database stock;' -U postgres
  - psql -d stock -a -f ../template.sql
  - cd ..
  - python server.py &
  - sleep 1 # give it some time to start
  - cd application
install:
  - cd application
  - pip install -r requirements.txt
  - pip install coveralls
  
script: coverage run --source=. --omit=algo_unitest.py,manage.py  manage.py


after_success:
  coveralls
 
