language: python

notifications:
  email: false

services:
  - postgresql

before_script:
  - psql -c 'create database stock;' -U postgres
  - psql -d HIGHWAYS -a -f template.sql

install:
  - cd application
  - pip install -r requirements.txt
  
  
script: python test.py

 
